name: build-test-worker-operator
on:
  pull_request:
    branches:
    - 'master'
    - 'release-*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v6
        with:
          tags: worker-operator:latest
          push: false
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v6
        with:
          file: test.Dockerfile
          tags: test-image:latest
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: make test
